name: Pull translated files and open pull request
run-name: Pull [${{ github.event.pull_request.base.ref }}] ${{ github.event.after }}
on: 
  workflow_run:
    workflows: ["Push to Lokalise from branch"]
    types:     
    - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Setup Git and Create New Branch
        run: |
                git config --global user.name "${GITHUB_ACTOR}"
                git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
                git checkout -b lokalise/${{ github.run_number }}

      - name: Lokalise CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

      - name: Download translated files
        env: 
          VAR_LOKALISE_API_TOKEN: ${{ secrets.API_TOKEN }}
          VAR_LOKALISE_PROJECT_ID: ${{ vars.PROJECT_ID }}
        run: |
             ./bin/lokalise2 --token ${{ env.VAR_LOKALISE_API_TOKEN }} --project-id ${{ env.VAR_LOKALISE_PROJECT_ID }} file download --format json --filter-langs=de --original-filenames=true --directory-prefix=/
            

          
      - name: Commit and Push Changes
        env: 
          GH_TOKEN: ${{ github.token }}
        run: |
             git add ./public/locales/\*.json
             if [[ -z $(git status --untracked-files=no --porcelain) ]]
             then
              echo "No changes"
             else
              git commit -m 'Translations update'
              git push --set-upstream origin lokalise/${{ github.run_number }}
             fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: lokalise/${{ github.run_number }}
          base: ${{ github.event.workflow_run.head_branch }}
          title: 'Translations update from Lokalise'
          body: 'Translation updates'